worker_processes  1;

events { worker_connections 1024; }

http {
    # Configuración de rate limiting para la API, limitando a 15 solicitudes por segundo por IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=15r/s;

    # Para evitar que el backend se marque como caído demasiado rápido, configuramos max_fails y fail_timeout
    upstream api_backend { 
        server api:8000 max_fails=3 fail_timeout=30s; 
    }

    # Configuración de logs para escribir en el volumen compartido
    access_log /var/log/nginx/access.log; 
    error_log /var/log/nginx/error.log warn;

    server {
        listen 80;

        # Configuración de rate limiting para la ruta /events, aplicando la zona api_limit con un burst de 2000 y sin delay
        location /events {
            limit_req zone=api_limit burst=1000 nodelay;
            proxy_pass http://api_backend;
        }
    }
}
